from diesis.abi.generated import (
    BOOTSTRAPCONFIG_ABI,
    DIESISCONFIG_ABI,
    DIESISPRIVACYPOOLS_ABI,
    DIESISSHIELDEDPOOL_ABI,
    IDIESISBOOTSTRAPORACLE_ABI,
    IDIESISPOSITION_ABI,
    ILIQUIDSTAKEDDS_ABI,
    IWRAPPEDDS_ABI,
)


def test_genesis_contract_abis_are_exported() -> None:
    assert BOOTSTRAPCONFIG_ABI
    assert DIESISCONFIG_ABI
    assert DIESISPRIVACYPOOLS_ABI
    assert DIESISSHIELDEDPOOL_ABI
    assert IDIESISBOOTSTRAPORACLE_ABI
    assert IDIESISPOSITION_ABI
    assert ILIQUIDSTAKEDDS_ABI
    assert IWRAPPEDDS_ABI
